type BuyingDelta {
  old: Int
  new: Int
  delta: Float
}

type SellingDelta {
  old: Int
  new: Int
  delta: Float
}

type OverallDelta {
  old: Int
  new: Int
  delta: Float
}

type ItemDelta {
  id: Int!
  name: String
  buyingDelta: [BuyingDelta]
  sellingDelta: [SellingDelta]
  overallDelta: [OverallDelta]
}
