# A representation of a Grand Exchange transaction
# expressed in a second-based epoch, the price at which an
# item was bought, the volume which was bought or
# attempted to buy, the price at which an item was sold,
# the volume which was or attempted to sell and the
# average price at which items were exchanged and which
# at which volume. Most values are expressed in strings,
# because of the 32-bit limitations of the GraphQL integer
# spec.
type RSBuddy {
  timestamp: String!
  buyingPrice: String
  buyingPriceDelta: Float
  buyingCompleted: String
  buyingCompletedDelta: Float
  sellingPrice: String
  sellingPriceDelta: Float
  sellingCompleted: String
  sellingCompletedDelta: Float
  overallPrice: String
  overallPriceDelta: Float
  overallCompleted: String
  overallCompletedDelta: Float
}
